# Generated by Django 4.2.30 on 2026-05-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('study_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_history', to='tasks.subject'),
        ),
    ]
