server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # React SPA — barcha route'larni index.html ga yo'naltirish
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static fayllar uchun kesh
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
