# Generated by Django 4.2.30 on 2026-05-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon', models.CharField(max_length=100)),
                ('required_count', models.PositiveIntegerField()),
                ('achievement_type', models.CharField(choices=[('task_count', 'Task Count'), ('streak', 'Streak'), ('consistency', 'Consistency'), ('weekly_goal', 'Weekly Goal')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
            ],
        ),
    ]
