# Generated by Django 4.2.30 on 2026-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_deadline_alter_task_subject'),
        ('tasks', '0002_initial'),
    ]

    operations = [
    ]
